services:
  web:
    build: .
    container_name: whattocook_web
    environment:
      POSTGRES_USER: whattocook
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: whattocook
      DB_HOST: db
      DB_PORT: 5432
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: whattocook_db
    environment:
      POSTGRES_USER: whattocook
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: whattocook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
