# Generated by Django 5.2.17 on 2026-08-06 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFood', '0005_telegramaccountlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('quantity', models.CharField(blank=True, default='1 item', max_length=100)),
                ('checked', models.BooleanField(default=False)),
                ('added_from', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['checked', '-created_at'],
            },
        ),
    ]
