"""
Django settings for WhatToCook project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Auto-load .env file if present
_env_file = BASE_DIR / ".env"
if _env_file.exists():
    with open(_env_file, "r", encoding="utf-8") as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                _k, _v = _k.strip(), _v.strip()
                if _k not in os.environ:
                    os.environ[_k] = _v


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

def _env_bool(name: str, default: str = "true") -> bool:
    return os.environ.get(name, default).strip().lower() not in ("0", "false", "no", "off")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-8@5!9rc+j+jm1p-d^jr!!h9#j&s%ev73o+occ&ll)5amw$c8l8",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", "true")

_IS_TESTING = "test" in [a for a in __import__("sys").argv]

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1,0.0.0.0" if DEBUG else "",
    ).split(",")
    if host.strip()
]
if not ALLOWED_HOSTS:
    raise RuntimeError(
        "ALLOWED_HOSTS must be set when DEBUG=false (see .env.example)."
    )

# ---------------------------------------------------------------------------
# Production security hardening (all tunable through the environment)
# ---------------------------------------------------------------------------
# When DEBUG=false we default every security switch to ON; set the matching
# env var to "false" to override behind a TLS-terminating proxy that already
# sets these headers itself.
_HTTPS = not DEBUG or _env_bool("FORCE_HTTPS", "false")

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")
X_FRAME_OPTIONS = "DENY"

# Only meaningful behind a TLS-terminating reverse proxy (nginx):
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if _env_bool("SECURE_SSL_REDIRECT", "true" if _HTTPS else "false"):
    SECURE_SSL_REDIRECT = True

SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", "true" if _HTTPS else "false")
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", "true" if _HTTPS else "false")
CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_HTTPONLY = True

if _env_bool("SECURE_HSTS", "true" if _HTTPS else "false"):
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Limit request bodies (the pantry scanner accepts uploads; don't let them be huge).
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(12 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", str(6 * 1024 * 1024)))



# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'GetFood',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WhatToCook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WhatToCook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

HAS_POSTGRES_DRIVER = False
try:
    import psycopg  # noqa
    HAS_POSTGRES_DRIVER = True
except ImportError:
    try:
        import psycopg2  # noqa
        HAS_POSTGRES_DRIVER = True
    except ImportError:
        HAS_POSTGRES_DRIVER = False

_use_postgres_env = os.environ.get("USE_POSTGRES", "").strip().lower()
_db_host = os.environ.get("DB_HOST", "").strip()

if _use_postgres_env in ("0", "false", "no"):
    # Explicit opt-out wins (e.g. running tests/bare-metal dev while .env targets Docker).
    USE_POSTGRES = False
else:
    USE_POSTGRES = (
        _use_postgres_env in ("1", "true", "yes")
        or bool(_db_host)
    ) and HAS_POSTGRES_DRIVER

if USE_POSTGRES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "whattocook"),
            "USER": os.environ.get("POSTGRES_USER", "whattocook"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "secret"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redirects after login/logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# CORS & CSRF Settings for React Frontend
# Dev default: every localhost origin. Production: set CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = DEBUG or _env_bool("CORS_ALLOW_ALL", "false")
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173",
    ).split(",")
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
DEFAULT_CSRF_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:4173',
    'http://127.0.0.1:4173',
]
CSRF_TRUSTED_ORIGINS = [
    *DEFAULT_CSRF_ORIGINS,
    *[o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()],
]

# AI Configuration (Google AI Studio Gemini + LM Studio)
AI_PROVIDER = os.getenv("AI_PROVIDER", "gemini")  # "gemini" or "lmstudio"
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.5-flash-lite")

LMSTUDIO_URL = os.getenv("LMSTUDIO_URL", "http://host.docker.internal:1234/v1/chat/completions")
MODEL_NAME = os.getenv("MODEL_NAME", "llama-3.2-3b-instruct")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        ['rest_framework.authentication.SessionAuthentication']
        + (['rest_framework.authentication.BasicAuthentication'] if DEBUG else [])
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # --- Rate limiting -------------------------------------------------
    # Endpoints declare their bucket(s) via GetFood.throttles.scoped(...);
    # unscoped endpoints (health/stats probes) are not throttled.
    'DEFAULT_THROTTLE_CLASSES': [],
    'DEFAULT_THROTTLE_RATES': {},
    'EXCEPTION_HANDLER': 'GetFood.throttles.wtc_exception_handler',
    'UNAUTHENTICATED_USER': 'django.contrib.auth.models.AnonymousUser',
}

# Production API is JSON-only (no browsable HTML forms/CSRF surface).
if not DEBUG:
    REST_FRAMEWORK.setdefault('DEFAULT_RENDERER_CLASSES', [
        'rest_framework.renderers.JSONRenderer',
    ])

# Runtime overridable rate table (see GetFood/rate_limits.load_rates).
# The test-suite keeps the throttle pipeline active but with effectively
# unlimited buckets, so 429 paths can be tested explicitly with
# override_settings while ordinary tests never trip a limit.
from GetFood.rate_limits import DEFAULT_RATES, load_rates

if _IS_TESTING:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        scope: "1000000/min" for scope in DEFAULT_RATES
    }
elif not _env_bool("THROTTLING_ENABLED", "true"):
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {}
else:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = load_rates()

# Celery: default to localhost for bare-metal dev; Docker sets redis://redis:6379/0 via .env
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Cache backend: Redis when REDIS_URL is provided (Docker), local-memory otherwise.
# This gives Redis a first-class job (hot-path caching) beyond the Celery broker role.
REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL.startswith("redis://"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "whattocook",
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "whattocook-local",
            "TIMEOUT": 300,
        }
    }


